"""initial schema

Revision ID: 3e988cd972ef
Revises: 
Create Date: 2026-04-12 13:17:07.533049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e988cd972ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('family_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_slug', sa.String(length=120), nullable=False),
    sa.Column('family_name', sa.String(length=160), nullable=False),
    sa.Column('profile_name', sa.String(length=120), nullable=False),
    sa.Column('profile_photo', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('family_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_profiles_family_slug'), ['family_slug'], unique=True)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('born', sa.String(length=32), nullable=False),
    sa.Column('died', sa.String(length=32), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('current_location_label', sa.String(length=255), nullable=False),
    sa.Column('current_location_lat', sa.Float(), nullable=True),
    sa.Column('current_location_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_public_id'), ['public_id'], unique=True)

    op.create_table('family_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=40), nullable=False),
    sa.Column('person_a_id', sa.Integer(), nullable=False),
    sa.Column('person_b_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_a_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_relationships_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_relationships_relationship_type'), ['relationship_type'], unique=False)

    op.create_table('person_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_migrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_migrations_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_migrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_migrations_person_id'))

    op.drop_table('person_migrations')
    with op.batch_alter_table('family_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_relationships_relationship_type'))
        batch_op.drop_index(batch_op.f('ix_family_relationships_family_id'))

    op.drop_table('family_relationships')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_public_id'))
        batch_op.drop_index(batch_op.f('ix_people_family_id'))

    op.drop_table('people')
    with op.batch_alter_table('family_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_profiles_family_slug'))

    op.drop_table('family_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
